<?php
/**
 *  This file was generated with crodas/SimpleView (https://github.com/crodas/SimpleView)
 *  Do not edit this file.
 *
 */

namespace {


    $GLOBALS['file_54c6de63df5ca'] = array();
    $GLOBALS['line_54c6de63df5ca'] = array();

    class base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {
        protected $parent;
        protected $child;
        protected $context;

        public function yield_parent($name, $args)
        {
            $method = "section_" . sha1($name);

            if (is_callable(array($this->parent, $method))) {
                $this->parent->$method(array_merge($this->context, $args));
                return true;
            }

            if ($this->parent) {
                return $this->parent->yield_parent($name, $args);
            }

            return false;
        }

        public function do_yield($name, Array $args = array())
        {
            if ($this->child) {
                // We have a children template, we are their base
                // so let's see if they have implemented by any change
                // this section
                if ($this->child->do_yield($name, $args)) {
                    // yes!
                    return true;
                }
            }

            // Do I have this section defined?
            $method = "section_" . sha1($name);
            if (is_callable(array($this, $method))) {
                // Yes!
                $this->$method(array_merge($this->context, $args));
                return true;
            }

            // No :-(
            return false;
        }

    }

    /** 
     *  Template class generated from loop1.tpl.php
     */
    class class_6be9d3fcb52ec7a4482d27fd52c23cd71db0613d extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'loop1.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            foreach($users as $id => $user) {

                $this->context['id'] = $id;
                $this->context['user'] = $user;
                $line_54c6de63df5ca[$_54c6de63df5ca] = 2;
                Tests\Templates::exec("loop1-example", $this->context);
                $line_54c6de63df5ca[$_54c6de63df5ca] = 3;
                if ($user == 1) {
                    continue;
                }
                $line_54c6de63df5ca[$_54c6de63df5ca] = 6;
            }
            $line_54c6de63df5ca[$_54c6de63df5ca] = 7;
            foreach($users as $user) {

                $this->context['user'] = $user;
                $line_54c6de63df5ca[$_54c6de63df5ca] = 8;
                Tests\Templates::exec("loop1-example", $this->context);
                break;
            }
            $line_54c6de63df5ca[$_54c6de63df5ca] = 11;

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from if1.tpl.php
     */
    class class_253d6a60b264956df48ba486a3d7908285d7ece5 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'if1.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            Tests\Templates::exec('if', $this->context);
            $line_54c6de63df5ca[$_54c6de63df5ca] = 2;

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from loop.tpl.php
     */
    class class_d481f16a4eb3add789581f97f6600c2a74a9d0a8 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'loop.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            foreach($users as $id => $user1) {

                $this->context['id'] = $id;
                $this->context['user1'] = $user1;
                $line_54c6de63df5ca[$_54c6de63df5ca] = 2;
                $user = $user1;
                $this->context['user'] = $user;
                $line_54c6de63df5ca[$_54c6de63df5ca] = 3;
                echo "    hi " . ($user) . "\n";
                $line_54c6de63df5ca[$_54c6de63df5ca] = 4;
                $foo = 'xxx';
                $this->context['foo'] = $foo;
                $line_54c6de63df5ca[$_54c6de63df5ca] = 5;
                if ($user == 1) {
                    continue;
                }
                $line_54c6de63df5ca[$_54c6de63df5ca] = 8;
            }
            $line_54c6de63df5ca[$_54c6de63df5ca] = 9;
            foreach($users as $user1) {

                $this->context['user1'] = $user1;
                $line_54c6de63df5ca[$_54c6de63df5ca] = 10;
                echo "    hi " . ($user1) . "\n";
                break;
            }
            $line_54c6de63df5ca[$_54c6de63df5ca] = 13;

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from extends.tpl.php
     */
    class class_793a0eb11fa5c92b689ad190f2f86f14ac827463 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {
        protected function section_8843d7f92416211de9ebb963ff4ce28125932878($context)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            extract($context);
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'foobar') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 4;
            $this->yield_parent('foobar', $context);
            $line_54c6de63df5ca[$_54c6de63df5ca] = 5;
            echo "    hi there!\n";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 6;
            array_pop($file_54c6de63df5ca);
        }

        public function hasSection($name)
        {
            switch ($name) {
            case 'foobar':
                return true;
            }

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

            ob_start();
            switch ($name) {
            case 'foobar':
                try {
                    $this->section_8843d7f92416211de9ebb963ff4ce28125932878($args);
                } catch (Exception $e) {
                    ob_get_clean();
                    throw $e;
                }
                break;
    
            }
    
            return ob_get_clean();
        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            $template = Tests\Templates::get("layout.tpl.php");
            $template->child = $this;
            $this->parent = $template;
            return $template->render($vars, $return);

        }
    }

    /** 
     *  Template class generated from while.tpl.php
     */
    class class_6e15d2af65fcf7798021e9323798f193499ac09d extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'while.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            while ($i < 10) {
                $line_54c6de63df5ca[$_54c6de63df5ca] = 2;
                echo "    hi " . (++$i) . "\n";
                $line_54c6de63df5ca[$_54c6de63df5ca] = 3;
            }
            $line_54c6de63df5ca[$_54c6de63df5ca] = 4;

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from home.tpl.php
     */
    class class_6caefdda43fcb619b729c17289d5237e623d208b extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'home.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            echo "Hello world\n";

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from loop2.tpl.php
     */
    class class_98c6e7085f21cfb73dcc0bf79490f712a83fa4e4 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'loop2.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            foreach($users as $id => $user) {

                $this->context['id'] = $id;
                $this->context['user'] = $user;
                echo "\n";
                $line_54c6de63df5ca[$_54c6de63df5ca] = 2;
                Tests\Templates::exec("loop1-example", $this->context);
                $line_54c6de63df5ca[$_54c6de63df5ca] = 3;
                echo "    ";
                if ($user == 1) {
                    echo "\n";
                    continue;
                }
                $line_54c6de63df5ca[$_54c6de63df5ca] = 6;
            }
            $line_54c6de63df5ca[$_54c6de63df5ca] = 7;
            foreach($users as $user) {

                $this->context['user'] = $user;
                $line_54c6de63df5ca[$_54c6de63df5ca] = 8;
                Tests\Templates::exec("loop1-example", $this->context);
                break;
            }
            $line_54c6de63df5ca[$_54c6de63df5ca] = 11;

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from mixed.tpl.php
     */
    class class_a1e3a95c79cab9e71f533a0b4f6234e4c760646d extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'mixed.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            foreach([1,2,3] as $auction) {

                $this->context['auction'] = $auction;
                $line_54c6de63df5ca[$_54c6de63df5ca] = 2;
                echo "      ";
                Tests\Templates::exec('home.tpl.php', $this->context);
                echo "\n";
                $line_54c6de63df5ca[$_54c6de63df5ca] = 3;
            }
            echo " \n";

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from exception.tpl.php
     */
    class class_bc5d54e4756cc431ce2b175b6469a7e430ac5a1f extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'exception.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            echo "Hi there\n!\n";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 3;
            echo failure() . "\nbye\n";

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from unless.tpl.php
     */
    class class_06bb1727fc549c9b2df4fe8a4d8f08d53ca2a1c8 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'unless.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            echo "Hi " . ($user['name']) . "\n";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 2;
            if (!($user['has_session'])) {
                $line_54c6de63df5ca[$_54c6de63df5ca] = 3;
                echo "    you must login\n";
                $line_54c6de63df5ca[$_54c6de63df5ca] = 4;
            }
            $line_54c6de63df5ca[$_54c6de63df5ca] = 5;

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from if.tpl.php
     */
    class class_75b4a0fe9cd1d6711cc7dec092e958edbe1efc00 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'if.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            echo "Hi ";
            echo htmlentities($name, ENT_QUOTES, 'UTF-8', false);
            echo "\n";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 2;
            if ($age < 18) {
                echo "\n    You cannot be here\n";
                $line_54c6de63df5ca[$_54c6de63df5ca] = 4;
            }
            else {
                $line_54c6de63df5ca[$_54c6de63df5ca] = 5;
                echo "    Welcome!\n";
                $line_54c6de63df5ca[$_54c6de63df5ca] = 6;
            }
            echo "\n";

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from at.tpl.php
     */
    class class_eef20d69ae52eb9005a515c213ab9554791979c9 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'at.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            var_export(['foo', 'bar']);
            echo "\n";

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from layout.tpl.php
     */
    class class_bf6970c3f5699b979a3692d8261f22d15fadad5a extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {
        protected function section_594fd1615a341c77829e83ed988f137e1ba96231($context)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            extract($context);
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'header') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 3;
            echo "<h1>Hi</h1>\n";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 4;
            array_pop($file_54c6de63df5ca);
        }
        protected function section_8843d7f92416211de9ebb963ff4ce28125932878($context)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            extract($context);
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'foobar') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 8;
            echo "    Nothing here\n";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 9;
            array_pop($file_54c6de63df5ca);
        }

        public function hasSection($name)
        {
            switch ($name) {
            case 'header':
            case 'foobar':
                return true;
            }

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

            ob_start();
            switch ($name) {
            case 'header':
                try {
                    $this->section_594fd1615a341c77829e83ed988f137e1ba96231($args);
                } catch (Exception $e) {
                    ob_get_clean();
                    throw $e;
                }
                break;
    
            case 'foobar':
                try {
                    $this->section_8843d7f92416211de9ebb963ff4ce28125932878($args);
                } catch (Exception $e) {
                    ob_get_clean();
                    throw $e;
                }
                break;
    
            }
    
            return ob_get_clean();
        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'foobar') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            echo "\n";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 2;
            $this->do_yield('header');
            $line_54c6de63df5ca[$_54c6de63df5ca] = 5;
            echo "\n<content>\n";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 7;
            $this->do_yield('foobar');
            $line_54c6de63df5ca[$_54c6de63df5ca] = 10;
            echo "</content>\n";

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from loop1-example.tpl.php
     */
    class class_f29db6e6f1c21db1b05b51162242fe0eafe8c136 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'loop1-example.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            echo "    hi " . ($user) . "\n";

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from spaceless.tpl.php
     */
    class class_066a64416ed54365eebbe9d553e59243995aa6ae extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function hasSection($name)
        {

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'spaceless.tpl.php') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;

            $line_54c6de63df5ca[$_54c6de63df5ca] = 2;
            echo "<h2>hi there</h2><h3>foo</h3>";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 4;
            if (true) {
                $line_54c6de63df5ca[$_54c6de63df5ca] = 5;
                echo "<h1>hi there</h1><b>dasda</b><h2>foo</h2>";
                $line_54c6de63df5ca[$_54c6de63df5ca] = 8;
            }
            $line_54c6de63df5ca[$_54c6de63df5ca] = 9;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 10;
            echo "\n";

            array_pop($file_54c6de63df5ca);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from extends_extends.tpl.php
     */
    class class_19709c42e2300830673895009607ec98d96822ec extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {
        protected function section_594fd1615a341c77829e83ed988f137e1ba96231($context)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            extract($context);
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'header') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 4;
            $this->yield_parent('header', $context);
            $line_54c6de63df5ca[$_54c6de63df5ca] = 5;
            echo "<h1>Bye</h1>\n";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 6;
            array_pop($file_54c6de63df5ca);
        }
        protected function section_8843d7f92416211de9ebb963ff4ce28125932878($context)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            extract($context);
            $_54c6de63df5ca = array_push($file_54c6de63df5ca, 'foobar') - 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 1;
            $line_54c6de63df5ca[$_54c6de63df5ca] = 9;
            $this->yield_parent('foobar', $context);
            $line_54c6de63df5ca[$_54c6de63df5ca] = 10;
            echo "    Bye there!\n";
            $line_54c6de63df5ca[$_54c6de63df5ca] = 11;
            array_pop($file_54c6de63df5ca);
        }

        public function hasSection($name)
        {
            switch ($name) {
            case 'header':
            case 'foobar':
                return true;
            }

            return false;
        }


        public function renderSection($name, Array $args = array(), $fail_on_missing = true)
        {
            if (!$this->hasSection($name)) {
                if ($fail_on_missing) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }
                return "";
            }

            ob_start();
            switch ($name) {
            case 'header':
                try {
                    $this->section_594fd1615a341c77829e83ed988f137e1ba96231($args);
                } catch (Exception $e) {
                    ob_get_clean();
                    throw $e;
                }
                break;
    
            case 'foobar':
                try {
                    $this->section_8843d7f92416211de9ebb963ff4ce28125932878($args);
                } catch (Exception $e) {
                    ob_get_clean();
                    throw $e;
                }
                break;
    
            }
    
            return ob_get_clean();
        }

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_get_clean();
                throw new Tests\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;
            $this->context = $vars;

            $template = Tests\Templates::get("extends");
            $template->child = $this;
            $this->parent = $template;
            return $template->render($vars, $return);

        }
    }

}

namespace Tests {

    use Exception;

    class ExceptionWrapper extends Exception
    {
        public $e;
        protected $file;

        public function getSimpleViewTrace()
        {
            global $file_54c6de63df5ca, $line_54c6de63df5ca;

            $traces = $this->e->getTrace();
            $i = 0;
            foreach ($traces as &$trace) {
                if (!empty($trace['file'])
                    && $trace['file'] == $this->file && !empty($file_54c6de63df5ca[$i])) {
                    $trace['file'] = $file_54c6de63df5ca[$i];
                    $trace['line'] = $line_54c6de63df5ca[$i];
                    ++$i;
                }
                if (empty($trace['file'])) {
                    $trace['file'] = '[internal function]';
                }
                if (empty($trace['line'])) {
                    $trace['line'] = '';
                }
            }

            return $traces;
        }

        public function __toString()
        {
            $traces = $this->getSimpleViewTrace();
            $str    = "exception '" . get_class($this->e) . "' in {$traces[0]['file']}{$traces[0]['line']}:\nStack trace:\n";
            foreach ($traces as $i => $trace) {
                $str .= "#{$i} {$trace['file']}:{$trace['line']}\n";
            }
            ++$i;
            $str .= "#{$i} {main}";
            return $str;
        }

        public function __construct(Exception $e, $file)
        {
            $this->e    = $e;
            $this->file = $file;
        }
    }


    class Templates
    {
        public static function getAll()
        {
            return array (
                0 => 'loop1',
                1 => 'if1',
                2 => 'loop',
                3 => 'extends',
                4 => 'while',
                5 => 'home',
                6 => 'loop2',
                7 => 'mixed',
                8 => 'exception',
                9 => 'unless',
                10 => 'if',
                11 => 'at',
                12 => 'layout',
                13 => 'loop1-example',
                14 => 'spaceless',
                15 => 'extends_extends',
            );
        }

        public static function getAllSections($name, $fail = true)
        {
            switch ($name) {
            case 'foobar':
                return array (
                    0 => 'extends.tpl.php',
                    1 => 'layout.tpl.php',
                    2 => 'extends_extends.tpl.php',
                );
            case 'header':
                return array (
                    0 => 'layout.tpl.php',
                    1 => 'extends_extends.tpl.php',
                );
            default:
                if ($fail) {
                    throw new \RuntimeException("Cannot find section {$name}");
                }

                return array();
            }
        }

        public static function exec($name, Array $context = array(), Array $global = array())
        {
            $tpl = self::get($name);
            return $tpl->render(array_merge($global, $context));
        }

        public static function get($name, Array $context = array())
        {
            static $classes = array (
                'loop1.tpl.php' => 'class_6be9d3fcb52ec7a4482d27fd52c23cd71db0613d',
                'loop1' => 'class_6be9d3fcb52ec7a4482d27fd52c23cd71db0613d',
                'if1.tpl.php' => 'class_253d6a60b264956df48ba486a3d7908285d7ece5',
                'if1' => 'class_253d6a60b264956df48ba486a3d7908285d7ece5',
                'loop.tpl.php' => 'class_d481f16a4eb3add789581f97f6600c2a74a9d0a8',
                'loop' => 'class_d481f16a4eb3add789581f97f6600c2a74a9d0a8',
                'extends.tpl.php' => 'class_793a0eb11fa5c92b689ad190f2f86f14ac827463',
                'extends' => 'class_793a0eb11fa5c92b689ad190f2f86f14ac827463',
                'while.tpl.php' => 'class_6e15d2af65fcf7798021e9323798f193499ac09d',
                'while' => 'class_6e15d2af65fcf7798021e9323798f193499ac09d',
                'home.tpl.php' => 'class_6caefdda43fcb619b729c17289d5237e623d208b',
                'home' => 'class_6caefdda43fcb619b729c17289d5237e623d208b',
                'loop2.tpl.php' => 'class_98c6e7085f21cfb73dcc0bf79490f712a83fa4e4',
                'loop2' => 'class_98c6e7085f21cfb73dcc0bf79490f712a83fa4e4',
                'mixed.tpl.php' => 'class_a1e3a95c79cab9e71f533a0b4f6234e4c760646d',
                'mixed' => 'class_a1e3a95c79cab9e71f533a0b4f6234e4c760646d',
                'exception.tpl.php' => 'class_bc5d54e4756cc431ce2b175b6469a7e430ac5a1f',
                'exception' => 'class_bc5d54e4756cc431ce2b175b6469a7e430ac5a1f',
                'unless.tpl.php' => 'class_06bb1727fc549c9b2df4fe8a4d8f08d53ca2a1c8',
                'unless' => 'class_06bb1727fc549c9b2df4fe8a4d8f08d53ca2a1c8',
                'if.tpl.php' => 'class_75b4a0fe9cd1d6711cc7dec092e958edbe1efc00',
                'if' => 'class_75b4a0fe9cd1d6711cc7dec092e958edbe1efc00',
                'at.tpl.php' => 'class_eef20d69ae52eb9005a515c213ab9554791979c9',
                'at' => 'class_eef20d69ae52eb9005a515c213ab9554791979c9',
                'layout.tpl.php' => 'class_bf6970c3f5699b979a3692d8261f22d15fadad5a',
                'layout' => 'class_bf6970c3f5699b979a3692d8261f22d15fadad5a',
                'loop1-example.tpl.php' => 'class_f29db6e6f1c21db1b05b51162242fe0eafe8c136',
                'loop1-example' => 'class_f29db6e6f1c21db1b05b51162242fe0eafe8c136',
                'spaceless.tpl.php' => 'class_066a64416ed54365eebbe9d553e59243995aa6ae',
                'spaceless' => 'class_066a64416ed54365eebbe9d553e59243995aa6ae',
                'extends_extends.tpl.php' => 'class_19709c42e2300830673895009607ec98d96822ec',
                'extends_extends' => 'class_19709c42e2300830673895009607ec98d96822ec',
            );
            $name = strtolower($name);
            if (empty($classes[$name])) {
                throw new \RuntimeException("Cannot find template $name");
            }

            $class = "\\" . $classes[$name];
            return new $class;
        }
    }

}
