<?php
/**
 *  This file was generated with crodas/SimpleView (https://github.com/crodas/SimpleView)
 *  Do not edit this file.
 *
 */

namespace {

    class base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {
        protected $parent;
        protected $child;
        protected $context;

        public function yield_parent($name, $args)
        {
            $method = "section_" . sha1($name);

            if (is_callable(array($this->parent, $method))) {
                $this->parent->$method(array_merge($this->context, $args));
                return true;
            }

            if ($this->parent) {
                return $this->parent->yield_parent($name, $args);
            }

            return false;
        }

        public function do_yield($name, Array $args = array())
        {
            if ($this->child) {
                // We have a children template, we are their base
                // so let's see if they have implemented by any change
                // this section
                if ($this->child->do_yield($name, $args)) {
                    // yes!
                    return true;
                }
            }

            // Do I have this section defined?
            $method = "section_" . sha1($name);
            if (is_callable(array($this, $method))) {
                // Yes!
                $this->$method(array_merge($this->context, $args));
                return true;
            }

            // No :-(
            return false;
        }

    }

    /** 
     *  Template class generated from loop1.tpl.php
     */
    class class_6be9d3fcb52ec7a4482d27fd52c23cd71db0613d extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            foreach($users as $id => $user) {

                Warning: explode() expects parameter 2 to be string, array given in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 98

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0461    3872480  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0462    3873520  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0462    3883864  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0462    3885016  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0462    3895456  17. explode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:98



                Warning: Invalid argument supplied for foreach() in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 103

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0461    3872480  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0462    3873520  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0462    3883864  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0462    3885016  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579

                Tests\Templates::exec("loop1-example", $this->context);
                if ($user == 1) {
                    continue;
                }
            }
            foreach($users as $user) {

                Warning: explode() expects parameter 2 to be string, array given in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 98

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0461    3872480  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0462    3873520  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0468    3885112  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0468    3886080  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0469    3896432  17. explode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:98



                Warning: Invalid argument supplied for foreach() in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 103

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0461    3872480  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0462    3873520  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0468    3885112  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0468    3886080  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579

                Tests\Templates::exec("loop1-example", $this->context);
                break;
            }

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from if1.tpl.php
     */
    class class_253d6a60b264956df48ba486a3d7908285d7ece5 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            Tests\Templates::exec('if', $this->context);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from loop.tpl.php
     */
    class class_d481f16a4eb3add789581f97f6600c2a74a9d0a8 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            foreach($users as $id => $user1) {

                Warning: explode() expects parameter 2 to be string, array given in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 98

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0475    3874024  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0475    3874904  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0475    3885168  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0475    3886136  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0475    3896488  17. explode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:98



                Warning: Invalid argument supplied for foreach() in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 103

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0475    3874024  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0475    3874904  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0475    3885168  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0475    3886136  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579

                $user = $user1;
                $this->context['user'] = $user;
                echo "    hi " . ($user) . "\n";
                $foo = 'xxx';
                $this->context['foo'] = $foo;
                if ($user == 1) {
                    continue;
                }
            }
            foreach($users as $user1) {

                Warning: explode() expects parameter 2 to be string, array given in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 98

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0475    3874024  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0475    3874904  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0481    3901704  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0481    3902672  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0481    3913024  17. explode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:98



                Warning: Invalid argument supplied for foreach() in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 103

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0475    3874024  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0475    3874904  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0481    3901704  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0481    3902672  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579

                echo "    hi " . ($user1) . "\n";
                break;
            }

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from extends.tpl.php
     */
    class class_793a0eb11fa5c92b689ad190f2f86f14ac827463 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {
        protected function section_8843d7f92416211de9ebb963ff4ce28125932878($context)
        {
            extract($context);
            $this->yield_parent('foobar', $context);
            echo "    hi there!\n";
        }

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            $template = Tests\Templates::get("layout.tpl.php");
            $template->child = $this;
            $this->parent = $template;
            return $template->render($vars, $return);

        }
    }

    /** 
     *  Template class generated from while.tpl.php
     */
    class class_6e15d2af65fcf7798021e9323798f193499ac09d extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            while ($i < 10) {
                echo "    hi " . (++$i) . "\n";
            }

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from home.tpl.php
     */
    class class_6caefdda43fcb619b729c17289d5237e623d208b extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            echo "Hello world\n";

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from loop2.tpl.php
     */
    class class_98c6e7085f21cfb73dcc0bf79490f712a83fa4e4 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            foreach($users as $id => $user) {

                Warning: explode() expects parameter 2 to be string, array given in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 98

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0488    3890944  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0488    3891912  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0488    3902496  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0488    3903552  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0488    3914136  17. explode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:98



                Warning: Invalid argument supplied for foreach() in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 103

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0488    3890944  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0488    3891912  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0488    3902496  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0488    3903552  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579

                echo "\n";
                Tests\Templates::exec("loop1-example", $this->context);
                echo "    ";
                if ($user == 1) {
                    echo "\n";
                    continue;
                }
            }
            foreach($users as $user) {

                Warning: explode() expects parameter 2 to be string, array given in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 98

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0488    3890944  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0488    3891912  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0494    3902496  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0494    3903552  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0494    3914136  17. explode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:98



                Warning: Invalid argument supplied for foreach() in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 103

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0488    3890944  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0488    3891912  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0494    3902496  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0494    3903552  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579

                Tests\Templates::exec("loop1-example", $this->context);
                break;
            }

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from mixed.tpl.php
     */
    class class_a1e3a95c79cab9e71f533a0b4f6234e4c760646d extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            foreach([1,2,3] as $auction) {

                Warning: explode() expects parameter 2 to be string, array given in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 98

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0500    3907328  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0500    3908296  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0500    3918880  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0500    3919936  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0500    3930520  17. explode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:98



                Warning: Invalid argument supplied for foreach() in /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php on line 103

                Call Stack:
                0.0001     234672   1. {main}() /usr/bin/phpunit:0
                0.0017     509376   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:46
                0.0017     510000   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:129
                0.0017     512408   4. PHPUnit_TextUI_Command->handleArguments() /usr/share/php/PHPUnit/TextUI/Command.php:138
                0.0038     865848   5. PHPUnit_TextUI_Command->handleBootstrap() /usr/share/php/PHPUnit/TextUI/Command.php:606
                0.0040     874264   6. PHPUnit_Util_Fileloader::checkAndLoad() /usr/share/php/PHPUnit/TextUI/Command.php:778
                0.0040     874464   7. PHPUnit_Util_Fileloader::load() /usr/share/php/PHPUnit/Util/Fileloader.php:76
                0.0040     882528   8. include_once('/home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php') /usr/share/php/PHPUnit/Util/Fileloader.php:92
                0.0074    1486960   9. crodas\SimpleView\Runtime->load() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/tests/bootstrap.php:22
                0.0454    3679080  10. crodas\SimpleView\Compiler->save() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Runtime.php:86
                0.0454    3679224  11. crodas\SimpleView\Compiler->getCode() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:123
                0.0461    3845376  12. class_ed71512c603ba20ba49346284ee12f19b5d744de->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Compiler.php:118
                0.0500    3907328  13. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:182
                0.0500    3908296  14. class_399877791885ad1a9fde51bca4deb52107f94699->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579
                0.0500    3918880  15. crodas\SimpleView\Templates\Templates::exec() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:443
                0.0500    3919936  16. class_55a865e988d24c0d11ce50bc8c11519a2d28b743->render() /home/crodas/projects/newest/SimpleViewEngine/SimpleView/lib/SimpleView/Templates.php:579

                echo "      ";
                Tests\Templates::exec('home.tpl.php', $this->context);
                echo "\n";
            }
            echo " \n";

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from unless.tpl.php
     */
    class class_06bb1727fc549c9b2df4fe8a4d8f08d53ca2a1c8 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            echo "Hi " . ($user['name']) . "\n";
            if (!($user['has_session'])) {
                echo "    you must login\n";
            }

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from if.tpl.php
     */
    class class_75b4a0fe9cd1d6711cc7dec092e958edbe1efc00 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            echo "Hi ";
            echo htmlentities($name, ENT_QUOTES, 'UTF-8', false);
            echo "\n";
            if ($age < 18) {
                echo "\n    You cannot be here\n";
            }
            else {
                echo "    Welcome!\n";
            }
            echo "\n";

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from at.tpl.php
     */
    class class_eef20d69ae52eb9005a515c213ab9554791979c9 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            var_export(['foo', 'bar']);
            echo "\n";

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from layout.tpl.php
     */
    class class_bf6970c3f5699b979a3692d8261f22d15fadad5a extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {
        protected function section_594fd1615a341c77829e83ed988f137e1ba96231($context)
        {
            extract($context);
            echo "<h1>Hi</h1>\n";
        }
        protected function section_8843d7f92416211de9ebb963ff4ce28125932878($context)
        {
            extract($context);
            echo "    Nothing here\n";
        }

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            echo "\n";
            $this->do_yield('header');
            echo "\n<content>\n";
            $this->do_yield('foobar');
            echo "</content>\n";

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from asset.tpl.php
     */
    class class_5c4c356a54a8ae3f2564a8edd5d2c39440cf8eed extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
        
            echo "cesar\n";
            $asset_url = '//foobar.com/assets/css/out.653d843f.min.css';
            echo "     <link href=\"" . ($asset_url) . "\" type=\"text/css\" rel=\"stylesheet\" />\n";

            echo "     <link href=\"" . ('//foobar.com/assets/css/out1.653d843f.min.css') . "\" type=\"text/css\" rel=\"stylesheet\" />\nrodas\n";

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from loop1-example.tpl.php
     */
    class class_f29db6e6f1c21db1b05b51162242fe0eafe8c136 extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            echo "    hi " . ($user) . "\n";

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from spaceless.tpl.php
     */
    class class_066a64416ed54365eebbe9d553e59243995aa6ae extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            echo "<h2>hi there</h2><h3>foo</h3>";
            if (true) {
                echo "<h1>hi there</h1><b>dasda</b><h2>foo</h2>";
            }
            echo "\n";

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from extends_extends.tpl.php
     */
    class class_19709c42e2300830673895009607ec98d96822ec extends base_template_39fdec1194d94212b871a28b2aa04a73cd40fce1
    {
        protected function section_594fd1615a341c77829e83ed988f137e1ba96231($context)
        {
            extract($context);
            $this->yield_parent('header', $context);
            echo "<h1>Bye</h1>\n";
        }
        protected function section_8843d7f92416211de9ebb963ff4ce28125932878($context)
        {
            extract($context);
            $this->yield_parent('foobar', $context);
            echo "    Bye there!\n";
        }

        public function render(Array $vars = array(), $return = false)
        {
            $this->context = $vars;

            $template = Tests\Templates::get("extends");
            $template->child = $this;
            $this->parent = $template;
            return $template->render($vars, $return);

        }
    }

}

namespace Tests {

    class Templates
    {
        public static function getAll()
        {
            return array (
                0 => 'loop1',
                1 => 'if1',
                2 => 'loop',
                3 => 'extends',
                4 => 'while',
                5 => 'home',
                6 => 'loop2',
                7 => 'mixed',
                8 => 'unless',
                9 => 'if',
                10 => 'at',
                11 => 'layout',
                12 => 'asset',
                13 => 'loop1-example',
                14 => 'spaceless',
                15 => 'extends_extends',
            );
        }

        public static function exec($name, Array $context = array(), Array $global = array())
        {
            $tpl = self::get($name);
            return $tpl->render(array_merge($global, $context));
        }

        public static function get($name, Array $context = array())
        {
            static $classes = array (
                'loop1.tpl.php' => 'class_6be9d3fcb52ec7a4482d27fd52c23cd71db0613d',
                'loop1' => 'class_6be9d3fcb52ec7a4482d27fd52c23cd71db0613d',
                'if1.tpl.php' => 'class_253d6a60b264956df48ba486a3d7908285d7ece5',
                'if1' => 'class_253d6a60b264956df48ba486a3d7908285d7ece5',
                'loop.tpl.php' => 'class_d481f16a4eb3add789581f97f6600c2a74a9d0a8',
                'loop' => 'class_d481f16a4eb3add789581f97f6600c2a74a9d0a8',
                'extends.tpl.php' => 'class_793a0eb11fa5c92b689ad190f2f86f14ac827463',
                'extends' => 'class_793a0eb11fa5c92b689ad190f2f86f14ac827463',
                'while.tpl.php' => 'class_6e15d2af65fcf7798021e9323798f193499ac09d',
                'while' => 'class_6e15d2af65fcf7798021e9323798f193499ac09d',
                'home.tpl.php' => 'class_6caefdda43fcb619b729c17289d5237e623d208b',
                'home' => 'class_6caefdda43fcb619b729c17289d5237e623d208b',
                'loop2.tpl.php' => 'class_98c6e7085f21cfb73dcc0bf79490f712a83fa4e4',
                'loop2' => 'class_98c6e7085f21cfb73dcc0bf79490f712a83fa4e4',
                'mixed.tpl.php' => 'class_a1e3a95c79cab9e71f533a0b4f6234e4c760646d',
                'mixed' => 'class_a1e3a95c79cab9e71f533a0b4f6234e4c760646d',
                'unless.tpl.php' => 'class_06bb1727fc549c9b2df4fe8a4d8f08d53ca2a1c8',
                'unless' => 'class_06bb1727fc549c9b2df4fe8a4d8f08d53ca2a1c8',
                'if.tpl.php' => 'class_75b4a0fe9cd1d6711cc7dec092e958edbe1efc00',
                'if' => 'class_75b4a0fe9cd1d6711cc7dec092e958edbe1efc00',
                'at.tpl.php' => 'class_eef20d69ae52eb9005a515c213ab9554791979c9',
                'at' => 'class_eef20d69ae52eb9005a515c213ab9554791979c9',
                'layout.tpl.php' => 'class_bf6970c3f5699b979a3692d8261f22d15fadad5a',
                'layout' => 'class_bf6970c3f5699b979a3692d8261f22d15fadad5a',
                'asset.tpl.php' => 'class_5c4c356a54a8ae3f2564a8edd5d2c39440cf8eed',
                'asset' => 'class_5c4c356a54a8ae3f2564a8edd5d2c39440cf8eed',
                'loop1-example.tpl.php' => 'class_f29db6e6f1c21db1b05b51162242fe0eafe8c136',
                'loop1-example' => 'class_f29db6e6f1c21db1b05b51162242fe0eafe8c136',
                'spaceless.tpl.php' => 'class_066a64416ed54365eebbe9d553e59243995aa6ae',
                'spaceless' => 'class_066a64416ed54365eebbe9d553e59243995aa6ae',
                'extends_extends.tpl.php' => 'class_19709c42e2300830673895009607ec98d96822ec',
                'extends_extends' => 'class_19709c42e2300830673895009607ec98d96822ec',
            );
            $name = strtolower($name);
            if (empty($classes[$name])) {
                throw new \RuntimeException("Cannot find template $name");
            }

            $class = "\\" . $classes[$name];
            return new $class;
        }
    }

}
