<?php
/**
 *  This file was generated with crodas/SimpleView (https://github.com/crodas/SimpleView)
 *  Do not edit this file.
 *
 */

namespace {


    $GLOBALS['file_5419d7acdba9a'] = array();
    $GLOBALS['line_5419d7acdba9a'] = array();

    class base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {
        protected $parent;
        protected $child;
        protected $context;

        public function yield_parent($name, $args)
        {
            $method = "section_" . sha1($name);

            if (is_callable(array($this->parent, $method))) {
                $this->parent->$method(array_merge($this->context, $args));
                return true;
            }

            if ($this->parent) {
                return $this->parent->yield_parent($name, $args);
            }

            return false;
        }

        public function do_yield($name, Array $args = array())
        {
            if ($this->child) {
                // We have a children template, we are their base
                // so let's see if they have implemented by any change
                // this section
                if ($this->child->do_yield($name, $args)) {
                    // yes!
                    return true;
                }
            }

            // Do I have this section defined?
            $method = "section_" . sha1($name);
            if (is_callable(array($this, $method))) {
                // Yes!
                $this->$method(array_merge($this->context, $args));
                return true;
            }

            // No :-(
            return false;
        }

    }

    /** 
     *  Template class generated from Unless.tpl.php
     */
    class class_f5ab41dedb21a24081861ee6a36af5e59365a600 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Unless.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "if (!(" . ($token[1]) . ")) {\n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 2;
            crodas\SimpleView\Templates\Templates::exec("body", array('tpl' => $token[2]), $this->context);
            $line_5419d7acdba9a[$_5419d7acdba9a] = 3;
            echo "}\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Newline.tpl.php
     */
    class class_cfa7269ec959308c668047e4aa1cd1d833f91eb6 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Newline.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "\$line_" . ($hash) . "[\$_" . ($hash) . "] = ";
            var_export($token[1]);
            echo ";\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Foreach.tpl.php
     */
    class class_55a865e988d24c0d11ce50bc8c11519a2d28b743 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Foreach.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "foreach(" . ($token[1]) . ") {\n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 2;
            $vars = preg_split("/\bas\b/", $token[1], 2);
            $this->context['vars'] = $vars;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 3;
            $vars = explode("=>", $vars[1]);
            $this->context['vars'] = $vars;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 4;
            echo "\n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 5;
            foreach($vars as $var) {

                $this->context['var'] = $var;
                $line_5419d7acdba9a[$_5419d7acdba9a] = 6;
                echo "        \$this->context[";
                var_export(substr(trim($var),1));
                echo "] = " . (trim($var)) . ";\n";
                $line_5419d7acdba9a[$_5419d7acdba9a] = 7;
            }
            $line_5419d7acdba9a[$_5419d7acdba9a] = 8;
            crodas\SimpleView\Templates\Templates::exec('body', array('tpl' => $token[2]), $this->context);
            $line_5419d7acdba9a[$_5419d7acdba9a] = 9;
            echo "}\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Set.tpl.php
     */
    class class_c36eec984e05803cb157ccb02bc2517cf30266a3 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Set.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "    " . ($token[1]) . " = " . ($token[2]) . ";\n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 2;
            if (preg_match("/^\\$[a-z_][a-z_0-9]*$/i", trim($token[1]))) {
                $line_5419d7acdba9a[$_5419d7acdba9a] = 3;
                echo "        \$this->context[";
                var_export(substr(trim($token[1]), 1));
                echo "] = " . ($token[1]) . ";\n";
                $line_5419d7acdba9a[$_5419d7acdba9a] = 4;
            }
            $line_5419d7acdba9a[$_5419d7acdba9a] = 5;

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Class.tpl.php
     */
    class class_ed71512c603ba20ba49346284ee12f19b5d744de extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Class.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "<?php\n/**\n *  This file was generated with crodas/SimpleView (https://github.com/crodas/SimpleView)\n *  Do not edit this file.\n *\n */\n\nnamespace {\n\n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 10;
            $hash = uniqid();
            $this->context['hash'] = $hash;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 11;
            echo "\n\$GLOBALS['file_";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 12;
            echo $hash . "'] = array();\n\$GLOBALS['line_";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 13;
            echo $hash . "'] = array();\n\nclass base_template_";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 15;
            echo sha1($namespace) . "\n{\n    protected \$parent;\n    protected \$child;\n    protected \$context;\n\n    public function yield_parent(\$name, \$args)\n    {\n        \$method = \"section_\" . sha1(\$name);\n\n        if (is_callable(array(\$this->parent, \$method))) {\n            \$this->parent->\$method(array_merge(\$this->context, \$args));\n            return true;\n        }\n\n        if (\$this->parent) {\n            return \$this->parent->yield_parent(\$name, \$args);\n        }\n\n        return false;\n    }\n\n    public function do_yield(\$name, Array \$args = array())\n    {\n        if (\$this->child) {\n            // We have a children template, we are their base\n            // so let's see if they have implemented by any change\n            // this section\n            if (\$this->child->do_yield(\$name, \$args)) {\n                // yes!\n                return true;\n            }\n        }\n\n        // Do I have this section defined?\n        \$method = \"section_\" . sha1(\$name);\n        if (is_callable(array(\$this, \$method))) {\n            // Yes!\n            \$this->\$method(array_merge(\$this->context, \$args));\n            return true;\n        }\n\n        // No :-(\n        return false;\n    }\n\n}\n\n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 63;
            foreach($tpls as $name => $tpl) {

                $this->context['name'] = $name;
                $this->context['tpl'] = $tpl;
                $line_5419d7acdba9a[$_5419d7acdba9a] = 64;
                echo "    /** \n     *  Template class generated from ";
                $line_5419d7acdba9a[$_5419d7acdba9a] = 65;
                echo $tpl->getSource() . "\n     */\nclass class_";
                $line_5419d7acdba9a[$_5419d7acdba9a] = 67;
                echo sha1($name) . " extends base_template_" . (sha1($namespace)) . "\n{\n";
                $line_5419d7acdba9a[$_5419d7acdba9a] = 69;
                foreach($tpl->getSections() as $name => $code) {

                    $this->context['name'] = $name;
                    $this->context['code'] = $code;
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 70;
                    echo "    protected function section_" . (sha1($name)) . "(\$context)\n    {\n        global \$file_";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 72;
                    echo $hash . ", \$line_" . ($hash) . ";\n        extract(\$context);\n        \$_";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 74;
                    echo $hash . " = array_push(\$file_" . ($hash) . ", ";
                    var_export($name);
                    echo ") - 1;\n        \$line_";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 75;
                    echo $hash . "[\$_" . ($hash) . "] = 1;\n";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 76;
                    crodas\SimpleView\Templates\Templates::exec("body", array('tpl' => $code), $this->context);
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 77;
                    echo "        array_pop(\$file_" . ($hash) . ");\n    }\n";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 79;
                }
                $line_5419d7acdba9a[$_5419d7acdba9a] = 80;
                echo "\n    public function render(Array \$vars = array(), \$return = false)\n    {\n        try { \n            return \$this->_render(\$vars, \$return);\n        } catch (\\Exception \$e) {\n            if (\$return) ob_clean();\n            throw new ";
                $line_5419d7acdba9a[$_5419d7acdba9a] = 87;
                echo $namespace . "\\ExceptionWrapper(\$e, __FILE__);\n        }\n    }\n\n    public function _render(Array \$vars = array(), \$return = false)\n    {\n        global \$file_";
                $line_5419d7acdba9a[$_5419d7acdba9a] = 93;
                echo $hash . ", \$line_" . ($hash) . ";\n        \$this->context = \$vars;\n\n";
                $line_5419d7acdba9a[$_5419d7acdba9a] = 96;
                if ($tpl->getParent()) {
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 97;
                    echo "        \$template = " . ($namespace) . "\\Templates::get(" . ($tpl->getParent()) . ");\n        \$template->child = \$this;\n        \$this->parent = \$template;\n        return \$template->render(\$vars, \$return);\n\n";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 102;
                }
                else {
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 103;
                    echo "        extract(\$vars);\n        if (\$return) {\n            ob_start();\n        }\n        \$_";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 107;
                    echo $hash . " = array_push(\$file_" . ($hash) . ", ";
                    var_export($name);
                    echo ") - 1;\n        \$line_";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 108;
                    echo $hash . "[\$_" . ($hash) . "] = 1;\n\n";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 110;
                    crodas\SimpleView\Templates\Templates::exec("body", array('tpl' => $tpl), $this->context);
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 111;
                    echo "\n        array_pop(\$file_";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 112;
                    echo $hash . ");\n\n        if (\$return) {\n            return ob_get_clean();\n        }\n\n";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 118;
                }
                $line_5419d7acdba9a[$_5419d7acdba9a] = 119;
                echo "    }\n}\n\n";
                $line_5419d7acdba9a[$_5419d7acdba9a] = 122;
            }
            $line_5419d7acdba9a[$_5419d7acdba9a] = 123;
            echo "}\n\nnamespace ";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 125;
            echo $namespace . " {\n\nuse Exception;\n\nclass ExceptionWrapper extends Exception\n{\n    public \$e;\n    protected \$file;\n\n    public function getSimpleViewTrace()\n    {\n        global \$file_";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 136;
            echo $hash . ", \$line_" . ($hash) . ";\n\n        \$traces = \$this->e->getTrace();\n        \$i = 0;\n        foreach (\$traces as &\$trace) {\n            if (!empty(\$trace['file']) \n              && \$trace['file'] == \$this->file && !empty(\$file_";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 142;
            echo $hash . "[\$i])) {\n                \$trace['file'] = \$file_";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 143;
            echo $hash . "[\$i];\n                \$trace['line'] = \$line_";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 144;
            echo $hash . "[\$i];\n                ++\$i;\n            }\n            if (empty(\$trace['file'])) {\n                \$trace['file'] = '[internal function]';\n            } \n            if (empty(\$trace['line'])) {\n                \$trace['line'] = '';\n            }\n        }\n\n        return \$traces;\n    }\n\n    public function __toString()\n    {\n        \$traces = \$this->getSimpleViewTrace();\n        \$str    = \"exception '\" . get_class(\$this->e) . \"' in {\$traces[0]['file']}{\$traces[0]['line']}:\\nStack trace:\\n\";\n        foreach (\$traces as \$i => \$trace) {\n            \$str .= \"#{\$i} {\$trace['file']}:{\$trace['line']}\\n\";\n        }\n        ++\$i;\n        \$str .= \"#{\$i} {main}\";\n        return \$str;\n    }\n\n    public function __construct(Exception \$e, \$file)\n    {\n        \$this->e    = \$e;\n        \$this->file = \$file;\n    }\n}\n\n\nclass Templates\n{\n    public static function getAll()\n    {\n        return ";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 182;
            var_export($list);
            echo ";\n    }\n\n    public static function exec(\$name, Array \$context = array(), Array \$global = array())\n    {\n        \$tpl = self::get(\$name);\n        return \$tpl->render(array_merge(\$global, \$context));\n    }\n\n    public static function get(\$name, Array \$context = array())\n    {\n        static \$classes = ";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 193;
            var_export($classes);
            echo ";\n        \$name = strtolower(\$name);\n        if (empty(\$classes[\$name])) {\n            throw new \\RuntimeException(\"Cannot find template \$name\");\n        }\n\n        \$class = \"\\\\\" . \$classes[\$name];\n        return new \$class;\n    }\n}\n\n}\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Echo.tpl.php
     */
    class class_1708ebe9d99ba4e58c0ae7fffeacd2f3eee56157 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Echo.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "echo " . ($token[1]) . ";\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Else.tpl.php
     */
    class class_55654f0db518414907f78793b7d027601d43ad01 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Else.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "else {\n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 2;
            crodas\SimpleView\Templates\Templates::exec("body", array('tpl' => $token[1]), $this->context);
            $line_5419d7acdba9a[$_5419d7acdba9a] = 3;
            echo "}\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Spaceless.tpl.php
     */
    class class_e5f3aacac71e677703efc7f7d2621463a25e5059 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Spaceless.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            crodas\SimpleView\Templates\Templates::exec("body", array('tpl' => $token[1]), $this->context);
            $line_5419d7acdba9a[$_5419d7acdba9a] = 2;

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from While.tpl.php
     */
    class class_6b1bcd97e93ed2c0cb9aac64a2ca1db0d5c1bbfd extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'While.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "while (" . ($token[1]) . ") {\n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 2;
            crodas\SimpleView\Templates\Templates::exec("body", array('tpl' => $token[2]), $this->context);
            $line_5419d7acdba9a[$_5419d7acdba9a] = 3;
            echo "}\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Yield.tpl.php
     */
    class class_a7fd4ba6aa8322c865f773ab9961440df3ccad7e extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Yield.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "\$this->do_yield(" . ($token[1]) . ");\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Echox.tpl.php
     */
    class class_b3f21f4b7452906b330612b966219cc089b11145 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Echox.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "echo htmlentities(" . ($token[1]) . ", ENT_QUOTES, 'UTF-8', false);\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from If.tpl.php
     */
    class class_47c00cca182fe3bc9f62a5b97ca88b8096be84f9 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'If.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "if (" . ($token[1]) . ") {\n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 2;
            crodas\SimpleView\Templates\Templates::exec("body", array('tpl' => $token[2]), $this->context);
            $line_5419d7acdba9a[$_5419d7acdba9a] = 3;
            echo "} \n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 4;
            if (!empty($token[3])) {
                $line_5419d7acdba9a[$_5419d7acdba9a] = 5;
                crodas\SimpleView\Templates\Templates::exec("body", array('tpl' => $token[3]), $this->context);
                $line_5419d7acdba9a[$_5419d7acdba9a] = 6;
            }
            $line_5419d7acdba9a[$_5419d7acdba9a] = 7;

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from ElseIf.tpl.php
     */
    class class_29c582cf88090afb569826fab26c5ff2408174a6 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'ElseIf.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "else if (" . ($token[1]) . ") {\n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 2;
            crodas\SimpleView\Templates\Templates::exec("body", array('tpl' => $token[2]), $this->context);
            $line_5419d7acdba9a[$_5419d7acdba9a] = 3;
            echo "} \n";
            $line_5419d7acdba9a[$_5419d7acdba9a] = 4;
            if (!empty($token[3])) {
                $line_5419d7acdba9a[$_5419d7acdba9a] = 5;
                crodas\SimpleView\Templates\Templates::exec("body", array('tpl' => $token[3]), $this->context);
                $line_5419d7acdba9a[$_5419d7acdba9a] = 6;
            }
            $line_5419d7acdba9a[$_5419d7acdba9a] = 7;
            echo "\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Var_export.tpl.php
     */
    class class_4c7ae9b989b5399767f582c58a57086e7e11e353 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Var_export.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "var_export(" . ($token[1]) . ");\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Body.tpl.php
     */
    class class_399877791885ad1a9fde51bca4deb52107f94699 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Body.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            foreach($tpl->getStmts() as $token) {

                $this->context['token'] = $token;
                $line_5419d7acdba9a[$_5419d7acdba9a] = 2;
                if ($token instanceof \crodas\SimpleView\Macro\Base) {
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 3;
                    echo "        " . ($token->run($this->context)) . "\n";
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 4;
                }
                else {
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 5;
                    crodas\SimpleView\Templates\Templates::exec($token[0], array('token' => $token ), $this->context);
                    $line_5419d7acdba9a[$_5419d7acdba9a] = 6;
                }
                $line_5419d7acdba9a[$_5419d7acdba9a] = 7;
            }
            $line_5419d7acdba9a[$_5419d7acdba9a] = 8;

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Break.tpl.php
     */
    class class_f438effbfd0e1abc280c3a5fd5c49a6b609fdece extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Break.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "    break;\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Continue.tpl.php
     */
    class class_a5a85b8b99262519741caf9201827cb2a6a2b36f extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Continue.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "    continue;\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Parent.tpl.php
     */
    class class_5d7cda60ed67317c63462a7a3f97c1eaa6a18d4e extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Parent.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo "\$this->yield_parent(" . ($token[1]) . ", \$context);\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

    /** 
     *  Template class generated from Include.tpl.php
     */
    class class_6ab34a3d879c7067d4dc67f5af3a8dd380cd3156 extends base_template_a7583170cd46360a631dc3d57f152bbeb4c37551
    {

        public function render(Array $vars = array(), $return = false)
        {
            try {
                return $this->_render($vars, $return);
            } catch (\Exception $e) {
                if ($return) ob_clean();
                throw new crodas\SimpleView\Templates\ExceptionWrapper($e, __FILE__);
            }
        }

        public function _render(Array $vars = array(), $return = false)
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;
            $this->context = $vars;

            extract($vars);
            if ($return) {
                ob_start();
            }
            $_5419d7acdba9a = array_push($file_5419d7acdba9a, 'Include.tpl.php') - 1;
            $line_5419d7acdba9a[$_5419d7acdba9a] = 1;

            echo $namespace . "\\Templates::exec(" . ($token[1]) . ", \$this->context);\n";

            array_pop($file_5419d7acdba9a);

            if ($return) {
                return ob_get_clean();
            }

        }
    }

}

namespace crodas\SimpleView\Templates {

    use Exception;

    class ExceptionWrapper extends Exception
    {
        public $e;
        protected $file;

        public function getSimpleViewTrace()
        {
            global $file_5419d7acdba9a, $line_5419d7acdba9a;

            $traces = $this->e->getTrace();
            $i = 0;
            foreach ($traces as &$trace) {
                if (!empty($trace['file'])
                    && $trace['file'] == $this->file && !empty($file_5419d7acdba9a[$i])) {
                    //$trace['file'] = $file_5419d7acdba9a[$i];
                    $trace['line'] = $line_5419d7acdba9a[$i];
                    ++$i;
                }
                if (empty($trace['file'])) {
                    $trace['file'] = '[internal function]';
                }
                if (empty($trace['line'])) {
                    $trace['line'] = '';
                }
            }

            return $traces;
        }

        public function __toString()
        {
            $traces = $this->getSimpleViewTrace();
            $str    = "exception '" . get_class($this->e) . "' in {$traces[0]['file']}{$traces[0]['line']}:\nStack trace:\n";
            foreach ($traces as $i => $trace) {
                $str .= "#{$i} {$trace['file']}:{$trace['line']}\n";
            }
            ++$i;
            $str .= "#{$i} {main}";
            return $str;
        }

        public function __construct(Exception $e, $file)
        {
            $this->e    = $e;
            $this->file = $file;
        }
    }


    class Templates
    {
        public static function getAll()
        {
            return array (
                0 => 'unless',
                1 => 'newline',
                2 => 'foreach',
                3 => 'set',
                4 => 'class',
                5 => 'echo',
                6 => 'else',
                7 => 'spaceless',
                8 => 'while',
                9 => 'yield',
                10 => 'echox',
                11 => 'if',
                12 => 'elseif',
                13 => 'var_export',
                14 => 'body',
                15 => 'break',
                16 => 'continue',
                17 => 'parent',
                18 => 'include',
            );
        }

        public static function exec($name, Array $context = array(), Array $global = array())
        {
            $tpl = self::get($name);
            return $tpl->render(array_merge($global, $context));
        }

        public static function get($name, Array $context = array())
        {
            static $classes = array (
                'unless.tpl.php' => 'class_f5ab41dedb21a24081861ee6a36af5e59365a600',
                'unless' => 'class_f5ab41dedb21a24081861ee6a36af5e59365a600',
                'newline.tpl.php' => 'class_cfa7269ec959308c668047e4aa1cd1d833f91eb6',
                'newline' => 'class_cfa7269ec959308c668047e4aa1cd1d833f91eb6',
                'foreach.tpl.php' => 'class_55a865e988d24c0d11ce50bc8c11519a2d28b743',
                'foreach' => 'class_55a865e988d24c0d11ce50bc8c11519a2d28b743',
                'set.tpl.php' => 'class_c36eec984e05803cb157ccb02bc2517cf30266a3',
                'set' => 'class_c36eec984e05803cb157ccb02bc2517cf30266a3',
                'class.tpl.php' => 'class_ed71512c603ba20ba49346284ee12f19b5d744de',
                'class' => 'class_ed71512c603ba20ba49346284ee12f19b5d744de',
                'echo.tpl.php' => 'class_1708ebe9d99ba4e58c0ae7fffeacd2f3eee56157',
                'echo' => 'class_1708ebe9d99ba4e58c0ae7fffeacd2f3eee56157',
                'else.tpl.php' => 'class_55654f0db518414907f78793b7d027601d43ad01',
                'else' => 'class_55654f0db518414907f78793b7d027601d43ad01',
                'spaceless.tpl.php' => 'class_e5f3aacac71e677703efc7f7d2621463a25e5059',
                'spaceless' => 'class_e5f3aacac71e677703efc7f7d2621463a25e5059',
                'while.tpl.php' => 'class_6b1bcd97e93ed2c0cb9aac64a2ca1db0d5c1bbfd',
                'while' => 'class_6b1bcd97e93ed2c0cb9aac64a2ca1db0d5c1bbfd',
                'yield.tpl.php' => 'class_a7fd4ba6aa8322c865f773ab9961440df3ccad7e',
                'yield' => 'class_a7fd4ba6aa8322c865f773ab9961440df3ccad7e',
                'echox.tpl.php' => 'class_b3f21f4b7452906b330612b966219cc089b11145',
                'echox' => 'class_b3f21f4b7452906b330612b966219cc089b11145',
                'if.tpl.php' => 'class_47c00cca182fe3bc9f62a5b97ca88b8096be84f9',
                'if' => 'class_47c00cca182fe3bc9f62a5b97ca88b8096be84f9',
                'elseif.tpl.php' => 'class_29c582cf88090afb569826fab26c5ff2408174a6',
                'elseif' => 'class_29c582cf88090afb569826fab26c5ff2408174a6',
                'var_export.tpl.php' => 'class_4c7ae9b989b5399767f582c58a57086e7e11e353',
                'var_export' => 'class_4c7ae9b989b5399767f582c58a57086e7e11e353',
                'body.tpl.php' => 'class_399877791885ad1a9fde51bca4deb52107f94699',
                'body' => 'class_399877791885ad1a9fde51bca4deb52107f94699',
                'break.tpl.php' => 'class_f438effbfd0e1abc280c3a5fd5c49a6b609fdece',
                'break' => 'class_f438effbfd0e1abc280c3a5fd5c49a6b609fdece',
                'continue.tpl.php' => 'class_a5a85b8b99262519741caf9201827cb2a6a2b36f',
                'continue' => 'class_a5a85b8b99262519741caf9201827cb2a6a2b36f',
                'parent.tpl.php' => 'class_5d7cda60ed67317c63462a7a3f97c1eaa6a18d4e',
                'parent' => 'class_5d7cda60ed67317c63462a7a3f97c1eaa6a18d4e',
                'include.tpl.php' => 'class_6ab34a3d879c7067d4dc67f5af3a8dd380cd3156',
                'include' => 'class_6ab34a3d879c7067d4dc67f5af3a8dd380cd3156',
            );
            $name = strtolower($name);
            if (empty($classes[$name])) {
                throw new \RuntimeException("Cannot find template $name");
            }

            $class = "\\" . $classes[$name];
            return new $class;
        }
    }

}
