<?php
/**
 *  This file was generated with crodas/SimpleView (https://github.com/crodas/SimpleView)
 *  Do not edit this file.
 *
 */

namespace {

@set($hash, uniqid())

class base_template_{{ sha1($namespace) }}
{
    protected $parent;
    protected $child;
    protected $context;

    public function yield_parent($name, $args)
    {
        $method = "section_" . sha1($name);

        if (is_callable(array($this->parent, $method))) {
            $this->parent->$method(array_merge($this->context, $args));
            return true;
        }

        if ($this->parent) {
            return $this->parent->yield_parent($name, $args);
        }

        return false;
    }

    public function do_yield($name, Array $args = array())
    {
        if ($this->child) {
            // We have a children template, we are their base
            // so let's see if they have implemented by any change
            // this section
            if ($this->child->do_yield($name, $args)) {
                // yes!
                return true;
            }
        }

        // Do I have this section defined?
        $method = "section_" . sha1($name);
        if (is_callable(array($this, $method))) {
            // Yes!
            $this->$method(array_merge($this->context, $args));
            return true;
        }

        // No :-(
        return false;
    }

}

@foreach($tpls as $name => $tpl)
    /** 
     *  Template class generated from {{ $tpl->getSource() }}
     */
class class_{{sha1($name)}} extends base_template_{{ sha1($namespace) }}
{
    @foreach ($tpl->getSections() as $name => $code)
    protected function section_{{sha1($name)}}($context)
    {
        extract($context);
        @include("body", array('tpl' => $code))
    }
    @end

    public function hasSection($name)
    {
        @if ($tpl->getSections())
            switch ($name) {
            @foreach ($tpl->getSections() as $name => $code)
                case {{@$name}}:
            @end
                return true;
            }
        @end

        return false;
    }


    public function renderSection($name, Array $args = array(), $fail_on_missing = true)
    {
        if (!$this->hasSection($name)) {
            if ($fail_on_missing) {
                throw new \RuntimeException("Cannot find section {$name}");
            }
            return "";
        }

        @if ($tpl->getSections())
            ob_start();
            switch ($name) {
            @foreach ($tpl->getSections() as $name => $code)
            case {{@$name}}:
                try {
                    $this->section_{{sha1($name)}}($args);
                } catch (Exception $e) {
                    ob_get_clean();
                    throw $e;
                }
                break;
    
            @end
            }
    
            return ob_get_clean();
        @end
    }

    public function render(Array $vars = array(), $return = false)
    {
        try {
            return $this->_render($vars, $return);
        } catch (Exception $e) {
            if ($return) ob_get_clean();
            throw $e;
        }
    }

    public function _render(Array $vars = array(), $return = false)
    {
        $this->context = $vars;

        @if ($tpl->getParent())
        $template = {{$namespace}}\Templates::get({{ $tpl->getParent() }});
        $template->child = $this;
        $this->parent = $template;
        return $template->render($vars, $return);

        @else
        extract($vars);
        if ($return) {
            ob_start();
        }

        @include("body", array('tpl' => $tpl))

        if ($return) {
            return ob_get_clean();
        }

        @endif
    }
}

@end
}

namespace {{$namespace}} {


class Templates
{
    public static function getAll()
    {
        return {{@$list}};
    }

    public static function getAllSections($name, $fail = true)
    {
        switch ($name) {
        @foreach ($sections as $name => $tpls)
        case {{@$name}}:
            return {{@$tpls}};
        @end
        default:
            if ($fail) {
                throw new \RuntimeException("Cannot find section {$name}");
            }

            return array();
        }
    }

    public static function exec($name, Array $context = array(), Array $global = array())
    {
        $tpl = self::get($name);
        return $tpl->render(array_merge($global, $context));
    }

    public static function get($name, Array $context = array())
    {
        static $classes = {{ @$classes }};
        $name = strtolower($name);
        if (empty($classes[$name])) {
            throw new \RuntimeException("Cannot find template $name");
        }

        $class = "\\" . $classes[$name];
        return new $class;
    }
}

}
